version: '3.8'

services:
  web:
    build: .
    command: /app/entrypoint.sh
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DEBUG=True # Set this to False in production
      - CELERY_BROKER_URL=redis://redis:6379/0
      # Add other environment variables like Django's SECRET_KEY, DEBUG, etc.

  db:
    image: postgres:13
    environment:
      - POSTGRES_DB=amie_todo_db
      - POSTGRES_USER=your_db_user
      - POSTGRES_PASSWORD=your_db_password
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  redis:
    image: "redis:latest"
    command: ["redis-server", "--appendonly", "yes"]
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  # celery:
  #   build: .
  #   command: celery -A amie worker --loglevel=info
  #   volumes:
  #     - .:/app
  #   depends_on:
  #     - db
  #     - redis
  #   environment:
  #     - CELERY_BROKER_URL=redis://redis:6379/0

volumes:
  postgres_data:
  redis_data:
