# Generated by Django 3.2 on 2023-06-15 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasklist',
            name='todoist_id',
            field=models.BigIntegerField(null=True),
        ),
    ]
