# Generated by Django 3.2 on 2023-06-15 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0002_alter_tasklist_todoist_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='todoist_id',
            field=models.BigIntegerField(null=True),
        ),
    ]
